version: '3.8'

services:
  server:
    image: pedronex/votala:1.0
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=mysql://root:pedrosilva@database:3306/votacao
      - JWT_SECRET=senhaSecreta
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mysql
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: pedrosilva
      MYSQL_DATABASE: votacao
      